service: my-express-application

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  hello:
    handler: lib/index.hello
    events:
      - http: ANY /hello
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 8080